package com.dimapp.android.homeyautomotive.repository

import android.content.Context
import android.util.Log
import com.dimapp.android.homeyautomotive.R
import com.dimapp.android.homeyautomotive.repository.models.HomeyDashboard
import com.dimapp.android.homeyautomotive.repository.models.HomeyResult
import com.dimapp.android.homeyautomotive.auth.HomeyAuthRepository
import com.dimapp.android.homeyautomotive.storage.TokenStorage

/**
 * Repository handling dashboard-related operations (fetching the Virtual Dashboard and its devices).
 * 
 * Note: This repository interacts exclusively with the "Virtual Dashboard" structure
 * generated by the Homey AAOS Companion App's settings, and does NOT access
 * native Homey dashboards.
 */
class DashboardRepository(
    context: Context,
    storage: TokenStorage,
    authRepo: HomeyAuthRepository
) : HomeyBaseRepository(context, storage, authRepo) {

    /**
     * Returns all custom dashboards provided by the Homey AAOS Companion App.
     */
    suspend fun getDashboards(): HomeyResult<List<HomeyDashboard>> {
        val service = _buildService() ?: return HomeyResult.Error(context.getString(R.string.repo_error_not_configured))

        return try {
            val response = service.getDashboards()
            if (!response.isSuccessful) {
                val errorBody = response.errorBody()?.string() ?: "no body"
                Log.e("DashboardRepository", "getDashboards HTTP ${response.code()} — error body: $errorBody")
                return HomeyResult.Error(context.getString(R.string.repo_error_dashboards_http, response.code()))
            }

            val dashboards = (response.body() ?: emptyMap())
                .values
                .map { 
                    HomeyDashboard(
                        id = it.id, 
                        name = context.getString(R.string.source_dashboard_title)
                    ) 
                }
                .sortedBy { it.name }

            HomeyResult.Success(dashboards)
        } catch (e: Exception) {
            HomeyResult.Error(context.getString(R.string.repo_error_conn_failed, e.message ?: "Unknown error"))
        }
    }

    /**
     * Retrieves the set of device UUIDs that belong to a given dashboard's widgets.
     */
    suspend fun getDashboardDeviceIds(dashboardId: String): HomeyResult<Set<String>> {
        val service = _buildService() ?: return HomeyResult.Error(context.getString(R.string.repo_error_not_configured))

        return try {
            val dashboardResponse = service.getDashboards()
            if (!dashboardResponse.isSuccessful) {
                return HomeyResult.Error(context.getString(R.string.repo_error_dashboards_http, dashboardResponse.code()))
            }

            val dashboard = dashboardResponse.body()?.get(dashboardId)
                ?: return HomeyResult.Error(context.getString(R.string.repo_error_dashboard_not_found, dashboardId))

            val dashboardDeviceIds = dashboard.columns
                .flatMap { column -> column.widgets }
                .filter { widget -> widget.type == "devices_custom" }
                .flatMap { widget -> widget.data?.deviceIds ?: emptyList() }
                .toSet()

            Log.d("DashboardRepository", "getDashboardDeviceIds for $dashboardId: found ${dashboardDeviceIds.size} device IDs.")
            HomeyResult.Success(dashboardDeviceIds)
        } catch (e: Exception) {
            HomeyResult.Error(context.getString(R.string.repo_error_conn_failed, e.message ?: "Unknown error"))
        }
    }
}
